sudo: required
services:
  - docker

before_install: 
  - docker build -t mkalia31/docker-react -f Dockerfile.dev .

script: 
CI=true npm test
  - docker run mkalia31/docker-react npm run test -- --coverage