sudo: required
services:
  - docker

before_install: 
  - docker build -t mkalia31/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true mkalia31/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "dockerreact-env"
  bucket-name: "elasticbeanstalk-us-east-1-243204323945"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS-ACCESS-KEY
  secret_access_key: "$AWS-SECRET-KEY"